title: "Ahmed"
email: ahmedsharifkhannoor@gmail.com
timezone: UTC
baseurl: "/ahmed"
url: "https://ahmedsharifkhan.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Ahmed Sharif Khan
    display_name: Ahmed Sharif Khan
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://ahmedsharifkhan.github.io/
    twitter: https://twitter.com/maxnoor87
    description: "Author of Ahmed Sharif Khan Noor."
  john:
    name: Ahmed
    display_name: Ahmed
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://ahmedsharifkhan.github.io
    twitter: https://twitter.com/maxnoor87
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/ahmedsharifkhannoor
  facebook: https://www.facebook.com/ahmedsharifkhannoor
  twitter: https://twitter.com/maxnoor87

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives